# Site based on Beautiful Jekyll! https://beautifuljekyll.com

# --- Required options --- #

# Name of website
title: JasonConger.com

twitter:
  username: JasonConger
  card: summary_large_image
social:
  name: Jason Conger
  links:
    - https://twitter.com/JasonConger
    - https://www.linkedin.com/in/JasonConger
    - https://github.com/JasonConger

# Authors
authors:
  JasonConger:
    name: Jason Conger
    display_name: Jason Conger
    gravatar: 405de84ebc6885c27b89c0fc35d222eb
    email: jason@jasonconger.com
    web: http://www.jasonconger.com
    twitter: https://twitter.com/JasonConger
    description: "I know more of what you should not do than what you should do"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/jcc-128.png"


# --- General options --- #

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 75

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "conger,splunk,citrix,microsoft,azure"

# --- Colors / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-X85BPW0Z1W"

# Google Tag Manager ID
gtm: "G-X85BPW0Z1W"

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
disqus: "jasonconger"

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
include: ["_pages"]

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

seo: "jekyll-seo-tag"

# Based on Beautiful Jekyll / Dean Attali