# Site
name: "JasonConger.com"
title: "JasonConger.com"
description: "Your source for extending virtual environments"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-346917-1'
disqus: 'jasonconger'
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jason:
    name: Jason Conger
    display_name: Jason Conger
    gravatar: 405de84ebc6885c27b89c0fc35d222eb
    email: jason@jasonconger.com
    web: http://www.jasonconger.com
    twitter: https://twitter.com/JasonConger
    description: "Description for Jason"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-5956187319902735"
adsense-data-ad-slot: "7593978519"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]